<style>
    .testimonial-item {
        transition: opacity 0.5s ease-in-out, transform 0.5s ease-in-out;
    }

    .fade-out {
        opacity: 0;
        transform: translateY(20px);
    }

    .fade-in {
        opacity: 1;
        transform: translateY(0);
    }

    .arrow-btn {
        transition: all 0.3s ease;
    }

    .arrow-btn:hover {
        transform: scale(1.1);
        background-color: rgba(59, 130, 246, 0.1);
    }

    .arrow-btn:active {
        transform: scale(0.95);
    }

    #testimonials {
        position: relative;
        background-image: url('{{ asset('landing/images/saudi arabia legal office video.jpg') }}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }

    #testimonials::before {
        content: "";
        position: absolute;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        /* adjust opacity here */
        z-index: 0;
    }

    .testimonials-body {
        z-index: 1000;
    }
</style>


<section id="testimonials" class="py-10 px-4">
    <div class="max-w-6xl testimonials-body mx-auto">
        <!-- Testimonial Container with proper positioning -->
        <div class="relative px-4 md:px-10 lg:px-24">


            <!-- Previous Arrow (Right side in RTL) -->
            <button id="prevBtn"
                class="arrow-btn absolute right-0 top-1/2 -translate-y-1/2 z-10 w-10 h-10 md:w-14 md:h-14 flex items-center justify-center rounded-full border-2  bg-white  shadow-lg focus:outline-none focus:ring-2 focus:ring-blue-400">
                <svg class="w-5 h-5 md:w-7 md:h-7 text-[#CF9411]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
            </button>

            <!-- Testimonial Card -->
            <div class="testimonial-item max-w-4xl mx-auto">


                <div class="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 md:p-10 lg:p-12 shadow-2xl">

                    <div class="text-center mb-12">
                        <h2 class="text-2xl font-bold text-gray-900 mb-4">
                            قصص نجاح
                        </h2>
                        <div class="w-24 h-1 bg-[#CF9411] mx-auto"></div>
                    </div>

                    <!-- Quote Icon -->
                    <div class="flex justify-center mb-6">
                        <svg class="w-10 h-10 md:w-12 md:h-12 text-[#CF9411] opacity-50" fill="currentColor"
                            viewBox="0 0 24 24">
                            <path
                                d="M9.983 3v7.391c0 5.704-3.731 9.57-8.983 10.609l-.995-2.151c2.432-.917 3.995-3.638 3.995-5.849h-4v-10h9.983zm14.017 0v7.391c0 5.704-3.748 9.571-9 10.609l-.996-2.151c2.433-.917 3.996-3.638 3.996-5.849h-3.983v-10h9.983z" />
                        </svg>
                    </div>

                    <!-- Testimonial Text -->
                    <div class="text-center mb-4">
                        <p id="testimonialText"
                            class="text-base  text-gray-700 leading-relaxed mb-2 min-h-[80px] md:min-h-[100px] flex items-center justify-center">
                            تم تحصيل مبلغ معدوم من المحامي خالد له عشرين سنة بمبلغ ستة عشر مليون وبعد التواصل مع المحامي
                            خالد تم تحصيل المبلغ بعد معاناة سنوات طويلة .
                        </p>
                    </div>
                </div>
            </div>

            <!-- Next Arrow (Left side in RTL) -->
            <button id="nextBtn"
                class="arrow-btn absolute left-0 top-1/2 -translate-y-1/2 z-10 w-10 h-10 md:w-14 md:h-14 flex items-center justify-center rounded-full border-2  bg-white  shadow-lg focus:outline-none focus:ring-2 focus:ring-blue-400">
                <svg class="w-5 h-5 md:w-7 md:h-7 text-[#CF9411]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
            </button>
        </div>

        <!-- Navigation Dots -->
        <div class="flex justify-center mt-12 gap-2" id="dotsContainer">
            <!-- Dots will be generated by JavaScript -->
        </div>
    </div>
</section>

<script>
    // Testimonials data
    const testimonials = [
        {
            text: "تم تحصيل مبلغ معدوم من المحامي خالد له عشرين سنة بمبلغ ستة عشر مليون وبعد التواصل مع المحامي خالد تم تحصيل المبلغ بعد معاناة سنوات طويلة .",
        },
        {
            text: "دين معدوم لدينا في الشركة استطاع الأستاذ تركي تحصليه بعد أن أخرج إفصاح من وزارة العدل بوجود أرض لدى المنفذ ضده، وتم عمل مزاد للأرض فكانت وسيلة ضغط على عميلنا للسداد..",
        },
        {
            text: "يملك الأستاذ تركي مهارة عالية في إقناع العميل بالسداد حيث كان لدى شركتنا أكثر من عميل متعثرين وعليهم تنفيذ لكن بدون جدوى في عملية السداد ،وبعد تواصل الأستاذ تركي معهم و إقناعهم بطرق احترافية تم تحصيل المبالغ من العملاء..",
        },
    ];

    let currentIndex = 0;
    let isAnimating = false;
    const testimonialText = document.getElementById('testimonialText');
    const testimonialItem = document.querySelector('.testimonial-item');
    const dotsContainer = document.getElementById('dotsContainer');
    let autoRotateInterval;

    // Create dots
    function createDots() {
        dotsContainer.innerHTML = '';
        testimonials.forEach((_, index) => {
            const dot = document.createElement('button');
            dot.className = `dot w-3 h-3 rounded-full transition-all duration-300 ${index === 0 ? 'bg-[#CF9411] w-8' : 'bg-[#CF9411]'
                }`;
            dot.setAttribute('data-index', index);
            dot.addEventListener('click', () => {
                if (!isAnimating) {
                    goToTestimonial(index);
                    resetAutoRotate();
                }
            });
            dotsContainer.appendChild(dot);
        });
    }

    // Update testimonial
    function updateTestimonial(index) {
        if (isAnimating || index === currentIndex) return;

        isAnimating = true;
        testimonialItem.classList.add('fade-out');

        setTimeout(() => {
            testimonialText.textContent = testimonials[index].text;
            currentIndex = index;

            // Update dots
            const dots = document.querySelectorAll('.dot');
            dots.forEach((dot, i) => {
                if (i === index) {
                    dot.classList.remove('bg-[#CF9411]', 'w-3');
                    dot.classList.add('bg-[#CF9411]', 'w-8');
                } else {
                    dot.classList.remove('bg-[#CF9411]', 'w-8');
                    dot.classList.add('bg-[#CF9411]', 'w-3');
                }
            });

            testimonialItem.classList.remove('fade-out');
            testimonialItem.classList.add('fade-in');

            setTimeout(() => {
                isAnimating = false;
            }, 100);
        }, 500);
    }

    // Go to specific testimonial
    function goToTestimonial(index) {
        if (index !== currentIndex && !isAnimating) {
            updateTestimonial(index);
        }
    }

    // Next testimonial
    function nextTestimonial() {
        if (!isAnimating) {
            const nextIndex = (currentIndex + 1) % testimonials.length;
            updateTestimonial(nextIndex);
        }
    }

    // Previous testimonial
    function prevTestimonial() {
        if (!isAnimating) {
            const prevIndex = (currentIndex - 1 + testimonials.length) % testimonials.length;
            updateTestimonial(prevIndex);
        }
    }

    // Auto-rotate testimonials
    function startAutoRotate() {
        autoRotateInterval = setInterval(() => {
            nextTestimonial();
        }, 6000);
    }

    // Reset auto-rotate
    function resetAutoRotate() {
        clearInterval(autoRotateInterval);
        startAutoRotate();
    }

    // Event listeners
    document.getElementById('nextBtn').addEventListener('click', () => {
        nextTestimonial();
        resetAutoRotate();
    });

    document.getElementById('prevBtn').addEventListener('click', () => {
        prevTestimonial();
        resetAutoRotate();
    });

    // Keyboard navigation
    document.addEventListener('keydown', (e) => {
        if (e.key === 'ArrowLeft') {
            nextTestimonial();
            resetAutoRotate();
        } else if (e.key === 'ArrowRight') {
            prevTestimonial();
            resetAutoRotate();
        }
    });

    // Pause on hover
    testimonialItem.addEventListener('mouseenter', () => {
        clearInterval(autoRotateInterval);
    });

    testimonialItem.addEventListener('mouseleave', () => {
        startAutoRotate();
    });

    // Initialize
    createDots();
    startAutoRotate();

    // Cleanup on page unload
    window.addEventListener('beforeunload', () => {
        clearInterval(autoRotateInterval);
    });
</script>