<style>
    .testimonial-item {
        transition: opacity 0.5s ease-in-out, transform 0.5s ease-in-out;
    }

    .fade-out {
        opacity: 0;
        transform: translateY(20px);
    }

    .fade-in {
        opacity: 1;
        transform: translateY(0);
    }

    .arrow-btn {
        transition: all 0.3s ease;
    }

    .arrow-btn:hover {
        transform: scale(1.1);
        background-color: rgba(59, 130, 246, 0.1);
    }
</style>

<section class="py-16 px-4 p-4"
    style="background-image: url('{{ asset('landing/images/saudi arabia legal office video.jpg') }}');">
    <div class="max-w-6xl mx-auto">
        <!-- Title -->
        <div class="text-center mb-12">
            <h2 class="text-2xl font-bold text-gray-100 mb-4">
                آراء العملاء
            </h2>
            <div class="w-24 h-1 bg-[#e2d392] mx-auto"></div>
        </div>

        <!-- Testimonial Container -->
        <div class="relative">
            <!-- Previous Arrow -->
            <button id="prevBtn"
                class="arrow-btn absolute right-0 top-1/2 -translate-y-1/2 z-10 w-12 h-12 md:w-16 md:h-16 flex items-center justify-center rounded-full border-2 border-gray-300 bg-white hover:border-blue-500 transition-all md:-right-20">
                <svg class="w-6 h-6 md:w-8 md:h-8 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                </svg>
            </button>

            <!-- Testimonial Card -->
            <div class="testimonial-item max-w-4xl mx-auto px-8 md:px-20">
                <div class="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-8 md:p-12 shadow-lg">
                    <!-- Quote Icon -->
                    <div class="flex justify-center mb-6">
                        <svg class="w-12 h-12 text-blue-500 opacity-50" fill="currentColor" viewBox="0 0 24 24">
                            <path
                                d="M9.983 3v7.391c0 5.704-3.731 9.57-8.983 10.609l-.995-2.151c2.432-.917 3.995-3.638 3.995-5.849h-4v-10h9.983zm14.017 0v7.391c0 5.704-3.748 9.571-9 10.609l-.996-2.151c2.433-.917 3.996-3.638 3.996-5.849h-3.983v-10h9.983z" />
                        </svg>
                    </div>

                    <!-- Testimonial Text -->
                    <div class="text-center mb-8">
                        <p id="testimonialText" class="text-lg md:text-xl text-gray-700 leading-relaxed mb-2">
                            They are capable of addressing all the detailed technical aspects of the case upon which the
                            legal issues rest.
                        </p>
                    </div>

                    <!-- Client Info -->
                    <div class="text-center border-t border-gray-300 pt-6">
                        <p id="clientInfo" class="text-base md:text-lg text-gray-600 font-medium">
                            Chambers and Partners Global 2025/Int'l Arbitration Client
                        </p>
                    </div>
                </div>
            </div>

            <!-- Next Arrow -->
            <button id="nextBtn"
                class="arrow-btn absolute left-0 top-1/2 -translate-y-1/2 z-10 w-12 h-12 md:w-16 md:h-16 flex items-center justify-center rounded-full border-2 border-gray-300 bg-white hover:border-blue-500 transition-all md:-left-20">
                <svg class="w-6 h-6 md:w-8 md:h-8 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
            </button>
        </div>

        <!-- Navigation Dots -->
        <div class="flex justify-center mt-12 gap-2" id="dotsContainer">
            <!-- Dots will be generated by JavaScript -->
        </div>
    </div>
</section>

<script>
    // Testimonials data
    const testimonials = [
        {
            text: "They are capable of addressing all the detailed technical aspects of the case upon which the legal issues rest.",
            client: "Chambers and Partners Global 2025/Int'l Arbitration Client"
        },
        {
            text: "فريق محترف للغاية ويقدم خدمات قانونية متميزة. لقد ساعدونا في حل قضايا معقدة بكفاءة عالية.",
            client: "عميل من القطاع الخاص - المملكة العربية السعودية"
        },
        {
            text: "Exceptional expertise in handling complex commercial disputes. Their attention to detail is outstanding.",
            client: "International Corporate Client - Dubai"
        },
        {
            text: "نشكر الفريق على الاحترافية والالتزام بالمواعيد. كانت النتائج أفضل من المتوقع.",
            client: "مؤسسة حكومية - الرياض"
        },
        {
            text: "Their strategic approach and deep understanding of regional laws made all the difference in our case.",
            client: "Legal Affairs Director - Multinational Corporation"
        }
    ];

    let currentIndex = 0;
    const testimonialText = document.getElementById('testimonialText');
    const clientInfo = document.getElementById('clientInfo');
    const testimonialItem = document.querySelector('.testimonial-item');
    const dotsContainer = document.getElementById('dotsContainer');
    let autoRotateInterval;

    // Create dots
    function createDots() {
        dotsContainer.innerHTML = '';
        testimonials.forEach((_, index) => {
            const dot = document.createElement('button');
            dot.className = `dot w-3 h-3 rounded-full transition-all ${index === 0 ? 'bg-blue-600 w-8' : 'bg-gray-300'}`;
            dot.setAttribute('data-index', index);
            dot.addEventListener('click', () => {
                goToTestimonial(index);
                resetAutoRotate();
            });
            dotsContainer.appendChild(dot);
        });
    }

    // Update testimonial
    function updateTestimonial(index) {
        testimonialItem.classList.add('fade-out');

        setTimeout(() => {
            testimonialText.textContent = testimonials[index].text;
            clientInfo.textContent = testimonials[index].client;
            currentIndex = index;

            // Update dots
            const dots = document.querySelectorAll('.dot');
            dots.forEach((dot, i) => {
                if (i === index) {
                    dot.classList.remove('bg-gray-300', 'w-3');
                    dot.classList.add('bg-blue-600', 'w-8');
                } else {
                    dot.classList.remove('bg-blue-600', 'w-8');
                    dot.classList.add('bg-gray-300', 'w-3');
                }
            });

            setTimeout(() => {
                testimonialItem.classList.remove('fade-out');
                testimonialItem.classList.add('fade-in');
            }, 50);
        }, 500);
    }

    // Go to specific testimonial
    function goToTestimonial(index) {
        if (index !== currentIndex) {
            updateTestimonial(index);
        }
    }

    // Next testimonial
    function nextTestimonial() {
        const nextIndex = (currentIndex + 1) % testimonials.length;
        updateTestimonial(nextIndex);
    }

    // Previous testimonial
    function prevTestimonial() {
        const prevIndex = (currentIndex - 1 + testimonials.length) % testimonials.length;
        updateTestimonial(prevIndex);
    }

    // Auto-rotate testimonials
    function startAutoRotate() {
        autoRotateInterval = setInterval(() => {
            nextTestimonial();
        }, 6000); // Change every 6 seconds
    }

    // Reset auto-rotate (useful when user manually navigates)
    function resetAutoRotate() {
        clearInterval(autoRotateInterval);
        startAutoRotate();
    }

    // Event listeners
    document.getElementById('nextBtn').addEventListener('click', () => {
        nextTestimonial();
        resetAutoRotate();
    });

    document.getElementById('prevBtn').addEventListener('click', () => {
        prevTestimonial();
        resetAutoRotate();
    });

    // Initialize
    createDots();
    startAutoRotate();
</script>
